export const FETCH_DEALS_BEGIN = 'FETCH_DEALS_BEGIN';
export const FETCH_DEALS_SUCCESS = 'FETCH_DEALS_SUCCESS';
export const FETCH_DEALS_FAILURE = 'FETCH_DEALS_FAILURE';

export const FETCH_SEARCHED_DEALS_BEGIN = 'FETCH_SEARCHED_DEALS_BEGIN';
export const FETCH_SEARCHED_DEALS_SUCCESS = 'FETCH_SEARCHED_DEALS_SUCCESS';
export const FETCH_SEARCHED_DEALS_FAILURE = 'FETCH_SEARCHED_DEALS_FAILURE';

export const FETCH_DEALS_BY_CATEGORY_BEGIN = 'FETCH_DEALS_BY_CATEGORY_BEGIN';
export const FETCH_DEALS_BY_CATEGORY_SUCCESS =
  'FETCH_DEALS_BY_CATEGORY_SUCCESS';
export const FETCH_DEALS_BY_CATEGORY_FAILURE =
  'FETCH_DEALS_BY_CATEGORY_FAILURE';
